/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Accessories;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Srinivasa Raghavan
 */
public class cal extends javax.swing.JFrame {

    /**
     * Creates new form cal
     */
    double plusminus,firstDouble,secondDouble,totalDouble;
    //To check for Button Clicks
     int plusClick;
     int minusClick,multiplyClick,divideClick,decimalClick;
    public cal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 255, 0));
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                formKeyReleased(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("BASIC CALCULATOR");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(60, 10, 333, 44);

        t1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t1ActionPerformed(evt);
            }
        });
        t1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                t1KeyReleased(evt);
            }
        });
        getContentPane().add(t1);
        t1.setBounds(10, 60, 460, 60);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 5));
        jPanel1.setLayout(null);

        jButton1.setText("3");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(190, 40, 60, 50);

        jButton7.setText("1");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7);
        jButton7.setBounds(30, 40, 60, 50);

        jButton8.setText("2");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8);
        jButton8.setBounds(110, 40, 60, 50);

        jButton9.setText("6");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton9);
        jButton9.setBounds(190, 110, 60, 50);

        jButton10.setText("5");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton10);
        jButton10.setBounds(110, 110, 60, 50);

        jButton11.setText("4");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton11);
        jButton11.setBounds(30, 110, 60, 50);

        jButton12.setText(".");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton12);
        jButton12.setBounds(190, 240, 60, 50);

        jButton13.setText("8");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton13);
        jButton13.setBounds(110, 180, 60, 50);

        jButton14.setText("7");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton14);
        jButton14.setBounds(30, 180, 60, 50);

        jButton15.setText("0");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton15);
        jButton15.setBounds(30, 240, 140, 50);

        jButton16.setText("9");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton16);
        jButton16.setBounds(190, 180, 60, 50);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 140, 280, 320);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 5));
        jPanel2.setLayout(null);

        jButton6.setText("C");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton6);
        jButton6.setBounds(20, 20, 60, 50);

        jButton4.setText("x");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4);
        jButton4.setBounds(20, 80, 60, 50);

        jButton2.setText("+");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(90, 20, 60, 50);

        jButton3.setText("-");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3);
        jButton3.setBounds(90, 80, 60, 50);

        jButton20.setText("SQR");
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton20);
        jButton20.setBounds(90, 200, 60, 50);

        jButton21.setText("Root");
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton21);
        jButton21.setBounds(20, 200, 60, 50);

        jButton17.setText("=");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton17);
        jButton17.setBounds(20, 260, 130, 50);

        jButton5.setText("/");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5);
        jButton5.setBounds(20, 140, 60, 50);

        jButton19.setText("~");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton19);
        jButton19.setBounds(90, 140, 60, 50);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(300, 140, 170, 320);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        t1.setText(t1.getText() + "5");
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        t1.setText(t1.getText() + "1");
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        t1.setText(t1.getText() + "2");
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        t1.setText(t1.getText() + "3");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        t1.setText(t1.getText() + "4");
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        t1.setText(t1.getText() + "6");
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        t1.setText(t1.getText() + "7");
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        t1.setText(t1.getText() + "8");
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
  if(decimalClick==0){
    t1.setText(t1.getText()+".");
    decimalClick=1;
    }
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        t1.setText(t1.getText() + "0");
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
     t1.setText("");
      decimalClick=0;
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
 firstDouble=(Double.parseDouble(String.valueOf(t1.getText())));
    t1.setText("");
    plusClick=1;
    decimalClick=0;
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    firstDouble=(Double.parseDouble(String.valueOf(t1.getText())));
    t1.setText("");
    minusClick=1;
    decimalClick=0;
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
    firstDouble=(Double.parseDouble(String.valueOf(t1.getText())));
    t1.setText("");
    multiplyClick=1;
    decimalClick=0;
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
   firstDouble=(Double.parseDouble(String.valueOf(t1.getText())));
    t1.setText("");
    divideClick=1;
    decimalClick=0;
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
  t1.setText(t1.getText() + "9");
    }//GEN-LAST:event_jButton16ActionPerformed

    private void t1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t1ActionPerformed
 secondDouble=(Double.parseDouble(String.valueOf(t1.getText())));
    if(plusClick>0){
    totalDouble=firstDouble+secondDouble;
    t1.setText(String.valueOf(totalDouble));
    firstDouble=0;
    secondDouble=0;
    plusClick=0;
    }
    if(minusClick>0){
    totalDouble=firstDouble-secondDouble;
    t1.setText(String.valueOf(totalDouble));
    firstDouble=0;
    secondDouble=0;
    minusClick=0;
    }
    if(multiplyClick>0){
    totalDouble=firstDouble*secondDouble;
    t1.setText(String.valueOf(totalDouble));
    firstDouble=0;
    secondDouble=0;
    multiplyClick=0;
    }
    if(divideClick>0){
    totalDouble=firstDouble/secondDouble;
    t1.setText(String.valueOf(totalDouble));
    firstDouble=0;
    secondDouble=0;
    divideClick=0;}
    }//GEN-LAST:event_t1ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
 secondDouble=(Double.parseDouble(String.valueOf(t1.getText())));
    if(plusClick>0){
    totalDouble=firstDouble+secondDouble;
    t1.setText(String.valueOf(totalDouble));
    firstDouble=0;
    secondDouble=0;
    plusClick=0;
    }
    if(minusClick>0){
    totalDouble=firstDouble-secondDouble;
    t1.setText(String.valueOf(totalDouble));
    firstDouble=0;
    secondDouble=0;
    minusClick=0;
    }
    if(multiplyClick>0){
    totalDouble=firstDouble*secondDouble;
    t1.setText(String.valueOf(totalDouble));
    firstDouble=0;
    secondDouble=0;
    multiplyClick=0;
    }
    if(divideClick>0){
    totalDouble=firstDouble/secondDouble;
    t1.setText(String.valueOf(totalDouble));
    firstDouble=0;
    secondDouble=0;
    divideClick=0;
    }    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
 double roundof,round;
    round=Double.parseDouble(t1.getText());
    roundof=Math.round(round);
    t1.setText(""+roundof);
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
double num,square;
    num=Double.parseDouble(t1.getText());
    square=num*num;
    t1.setText(""+square);
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
double num,root;
    num=Double.parseDouble(t1.getText());
    root=Math.sqrt(num);
    t1.setText(""+root);
    }//GEN-LAST:event_jButton21ActionPerformed

    private void t1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t1KeyReleased
if(evt.getKeyCode() == KeyEvent.VK_ENTER){
          secondDouble=(Double.parseDouble(String.valueOf(t1.getText())));
    if(plusClick>0){
    totalDouble=firstDouble+secondDouble;
    t1.setText(String.valueOf(totalDouble));
    firstDouble=0;
    secondDouble=0;
    plusClick=0;
    }
    if(minusClick>0){
    totalDouble=firstDouble-secondDouble;
    t1.setText(String.valueOf(totalDouble));
    firstDouble=0;
    secondDouble=0;
    minusClick=0;
    }
    if(multiplyClick>0){
    totalDouble=firstDouble*secondDouble;
    t1.setText(String.valueOf(totalDouble));
    firstDouble=0;
    secondDouble=0;
    multiplyClick=0;
    }
    if(divideClick>0){
    totalDouble=firstDouble/secondDouble;
    t1.setText(String.valueOf(totalDouble));
    firstDouble=0;
    secondDouble=0;
    divideClick=0;}}
    }//GEN-LAST:event_t1KeyReleased

    private void formKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyReleased
 if(evt.getKeyCode() == KeyEvent.VK_BACK_SPACE)
    {
        t1.setText(t1.getText().substring(0,(t1.getText()).length()));
    }

    if(evt.getKeyCode() == KeyEvent.VK_ESCAPE)
    {
   t1.setText("");
      decimalClick=0;
    }
     if(evt.getKeyCode() == KeyEvent.VK_ENTER){
          secondDouble=(Double.parseDouble(String.valueOf(t1.getText())));
    if(plusClick>0){
    totalDouble=firstDouble+secondDouble;
    t1.setText(String.valueOf(totalDouble));
    firstDouble=0;
    secondDouble=0;
    plusClick=0;
    }
    if(minusClick>0){
    totalDouble=firstDouble-secondDouble;
    t1.setText(String.valueOf(totalDouble));
    firstDouble=0;
    secondDouble=0;
    minusClick=0;
    }
    if(multiplyClick>0){
    totalDouble=firstDouble*secondDouble;
    t1.setText(String.valueOf(totalDouble));
    firstDouble=0;
    secondDouble=0;
    multiplyClick=0;
    }
    if(divideClick>0){
    totalDouble=firstDouble/secondDouble;
    t1.setText(String.valueOf(totalDouble));
    firstDouble=0;
    secondDouble=0;
    divideClick=0;}}
    }//GEN-LAST:event_formKeyReleased

    private void t1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t1KeyPressed
if(evt.getKeyCode() == KeyEvent.VK_ENTER){
          secondDouble=(Double.parseDouble(String.valueOf(t1.getText())));
    if(plusClick>0){
    totalDouble=firstDouble+secondDouble;
    t1.setText(String.valueOf(totalDouble));
    firstDouble=0;
    secondDouble=0;
    plusClick=0;
    }
    if(minusClick>0){
    totalDouble=firstDouble-secondDouble;
    t1.setText(String.valueOf(totalDouble));
    firstDouble=0;
    secondDouble=0;
    minusClick=0;
    }
    if(multiplyClick>0){
    totalDouble=firstDouble*secondDouble;
    t1.setText(String.valueOf(totalDouble));
    firstDouble=0;
    secondDouble=0;
    multiplyClick=0;
    }
    if(divideClick>0){
    totalDouble=firstDouble/secondDouble;
    t1.setText(String.valueOf(totalDouble));
    firstDouble=0;
    secondDouble=0;
    divideClick=0;}}

    }//GEN-LAST:event_t1KeyPressed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
 if(evt.getKeyCode() == KeyEvent.VK_BACK_SPACE)
    {
        t1.setText(t1.getText().substring(0,(t1.getText()).length()));
    }

    if(evt.getKeyCode() == KeyEvent.VK_ESCAPE)
    {
   t1.setText("");
      decimalClick=0;
    }
     if(evt.getKeyCode() == KeyEvent.VK_ENTER){
          secondDouble=(Double.parseDouble(String.valueOf(t1.getText())));
    if(plusClick>0){
    totalDouble=firstDouble+secondDouble;
    t1.setText(String.valueOf(totalDouble));
    firstDouble=0;
    secondDouble=0;
    plusClick=0;
    }
    if(minusClick>0){
    totalDouble=firstDouble-secondDouble;
    t1.setText(String.valueOf(totalDouble));
    firstDouble=0;
    secondDouble=0;
    minusClick=0;
    }
    if(multiplyClick>0){
    totalDouble=firstDouble*secondDouble;
    t1.setText(String.valueOf(totalDouble));
    firstDouble=0;
    secondDouble=0;
    multiplyClick=0;
    }
    if(divideClick>0){
    totalDouble=firstDouble/secondDouble;
    t1.setText(String.valueOf(totalDouble));
    firstDouble=0;
    secondDouble=0;
    divideClick=0;}}
    }//GEN-LAST:event_formKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField t1;
    // End of variables declaration//GEN-END:variables
}
