/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package User;

import java.awt.*;
import java.awt.event.KeyEvent;
import java.io.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;

/**
 *
 * @author malod
 */
public class Init extends javax.swing.JFrame {

    /**
     * Creates new form Init
     */
    public Init() {
        setUndecorated(true);
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        setBounds(100, 100, (int) dim.getWidth(), (int) dim.getHeight());
        setLocationRelativeTo(null);
        setVisible(true);
        File f = new File("C:\\JBOS\\");
        if (!f.exists()) {
            f.mkdir();
        }
        f = new File("C:\\JBOS\\OS_Data\\");
        if (!f.exists()) {
            f.mkdir();
        }
        f = new File("C:\\JBOS\\OS_Data\\Users\\");
        if (!f.exists()) {
            f.mkdir();
        }
        f = new File("C:\\JBOS\\Sys_files\\");
        if (!f.exists()) {
            f.mkdir();
        }
        f = new File("C:\\JBOS\\Sys_files\\data\\");
        if (!f.exists()) {
            f.mkdir();
        }
        jLabel1.setVisible(false);
        jLabel2.setVisible(false);
        jLabel3.setVisible(false);
        un.setVisible(false);
        p1.setVisible(false);
        p2.setVisible(false);
        en.setVisible(false);
        jButton1.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nu = new javax.swing.JButton();
        eu = new javax.swing.JButton();
        un = new javax.swing.JTextField();
        en = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        p1 = new javax.swing.JPasswordField();
        p2 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 255));
        setResizable(false);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                formKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                formKeyTyped(evt);
            }
        });
        getContentPane().setLayout(null);

        nu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/User/new user.jpg"))); // NOI18N
        nu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuActionPerformed(evt);
            }
        });
        getContentPane().add(nu);
        nu.setBounds(700, 340, 170, 136);

        eu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/User/old user.jpg"))); // NOI18N
        eu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                euActionPerformed(evt);
            }
        });
        eu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                euKeyTyped(evt);
            }
        });
        getContentPane().add(eu);
        eu.setBounds(420, 340, 170, 136);

        un.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unActionPerformed(evt);
            }
        });
        getContentPane().add(un);
        un.setBounds(604, 210, 303, 39);

        en.setText("Enter");
        en.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enActionPerformed(evt);
            }
        });
        getContentPane().add(en);
        en.setBounds(930, 260, 110, 40);

        jLabel1.setText("Confirm Password:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(470, 310, 110, 40);

        jLabel2.setText("Username:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(470, 210, 100, 40);

        jLabel3.setText("Password:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(470, 260, 100, 40);

        p1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p1ActionPerformed(evt);
            }
        });
        getContentPane().add(p1);
        p1.setBounds(600, 260, 310, 40);

        p2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p2ActionPerformed(evt);
            }
        });
        getContentPane().add(p2);
        p2.setBounds(600, 310, 310, 40);

        jButton1.setText("Back");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(310, 130, 80, 60);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("The OS is still under construction. This is a stable build version.");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(340, 580, 720, 80);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuActionPerformed
        nu.setVisible(false);
        eu.setVisible(false);
        jLabel1.setVisible(true);
        jLabel2.setVisible(true);
        jLabel3.setVisible(true);
        un.setVisible(true);
        p1.setVisible(true);
        p2.setVisible(true);
        en.setVisible(true);
        jButton1.setVisible(true);
        usr = "new";
        un.requestFocus();
    }//GEN-LAST:event_nuActionPerformed

    private void euActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_euActionPerformed
        nu.setVisible(false);
        eu.setVisible(false);
        jLabel3.setVisible(true);
        jLabel2.setVisible(true);
        un.setVisible(true);
        p1.setVisible(true);
        en.setVisible(true);
        jButton1.setVisible(true);
        usr = "old";
        un.requestFocus();
    }//GEN-LAST:event_euActionPerformed

    private void enActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enActionPerformed
        if (usr.equals("new")) {
            usrname = un.getText();
            pas = new String(p1.getPassword());
            cpas = new String(p2.getPassword());
            if (pas.equals(cpas)) {
                File f = new File("C:\\JBOS\\OS_Data\\Users\\" + usrname + "\\");
                if (!f.exists()) {
                    f.mkdir();
                    File ff = new File("C:\\JBOS\\OS_Data\\Users\\" + usrname + "\\acc.dat");
                    OutputStream out = null;
                    try {
                        out = new FileOutputStream(ff);
                        for (byte b : (usrname + "~" + pas).getBytes()) {
                            out.write(b);
                        }
                    } catch (IOException e1) {
                        e1.printStackTrace();
                    } finally {
                        if (out != null) {
                            try {
                                out.close();
                                out = null;
                            } catch (IOException e2) {
                                e2.printStackTrace();
                            }
                        }
                        ff = new File("C:\\JBOS\\OS_Data\\Users\\" + usrname + "\\wp.dat");
                        try {
                            out = new FileOutputStream(ff);
                            for (byte b : "/UI/imwp.jpg".getBytes()) {
                                out.write(b);
                            }
                        } catch (IOException e1) {
                            e1.printStackTrace();
                        } finally {
                            if (out != null) {
                                try {
                                    out.close();
                                    out = null;
                                } catch (IOException e2) {
                                    e2.printStackTrace();
                                }
                            }
                            UI.Basic b = null;
                            try {
                                b = new UI.Basic();
                            } catch (IOException ex) {
                                Logger.getLogger(Init.class.getName()).log(Level.SEVERE, null, ex);
                            }
                            this.setVisible(false);
                            b.setVisible(true);
                        }
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Account Exists. Change Username.");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Passwords Don't Match.");
            }
        } else if (usr.equals("old")) {
            try {
                usrname = un.getText();
                pas = new String(p1.getPassword());
                File f = new File("C:\\JBOS\\OS_Data\\Users\\" + usrname + "\\acc.dat");
                BufferedReader br = null;
                try {
                    br = new BufferedReader(new FileReader(f));
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(Init.class.getName()).log(Level.SEVERE, null, ex);
                }
                if (br.readLine().equals(usrname + "~" + pas)) {
                    UI.Basic b = new UI.Basic();
                    this.setVisible(false);
                    b.setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(this, "Account Doesn't Exist. Create User.");
                }
            } catch (IOException ex) {
                Logger.getLogger(Init.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_enActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        nu.setVisible(true);
        eu.setVisible(true);
        jLabel1.setVisible(false);
        jLabel2.setVisible(false);
        jLabel3.setVisible(false);
        un.setVisible(false);
        p1.setVisible(false);
        p2.setVisible(false);
        en.setVisible(false);
        jButton1.setVisible(false);
        un.setText("");
        p1.setText("");
        p2.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void unActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unActionPerformed
p1.requestFocus();
    }//GEN-LAST:event_unActionPerformed

    private void p1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p1ActionPerformed
if(usr.equals("old")) {enActionPerformed(evt);}
else p2.requestFocus();
    }//GEN-LAST:event_p1ActionPerformed

    private void p2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p2ActionPerformed
enActionPerformed(evt);
    }//GEN-LAST:event_p2ActionPerformed

    private void formKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyTyped
if(evt.getKeyCode()==KeyEvent.VK_ENTER) {
    eu.doClick();
}
if(evt.getKeyCode()==KeyEvent.VK_BACK_SPACE) {
    jButton1.doClick();
}
if(evt.getKeyCode()==KeyEvent.VK_R) {
    nu.doClick();
}
    }//GEN-LAST:event_formKeyTyped

    private void formKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyReleased

    }//GEN-LAST:event_formKeyReleased

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed

    }//GEN-LAST:event_formKeyPressed

    private void euKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_euKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_euKeyTyped

    /**
     * @param args the command line arguments
     */
    public static String usrname, usr, pas, cpas;

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Init.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Init.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Init.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Init.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Init().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton en;
    private javax.swing.JButton eu;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton nu;
    private javax.swing.JPasswordField p1;
    private javax.swing.JPasswordField p2;
    private javax.swing.JTextField un;
    // End of variables declaration//GEN-END:variables
}
